# Generated by Django 2.2 on 2020-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repo_type',
            field=models.CharField(choices=[('Amphora', 'Amphora')], default='Amphora', max_length=100),
        ),
    ]
