# Generated by Django 2.2 on 2020-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_repository_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_type',
            field=models.CharField(choices=[('Amphora', 'Amphora'), ('Citesphere', 'Citesphere')], default='Amphora', max_length=100),
        ),
    ]
