dist: bionic
language: python
python:
  - "3.7"
services:
  - redis-server
  - postgresql
addons:
    postgresql: '11'
    apt:
      packages:
        - postgresql-11
        - postgresql-client-11
env:
  global:
    - DJANGO_SETTINGS_MODULE=vogon.settings
    - REDIS_URL=redis://
    - CELERY_TASK_SERIALIZER=json
    - DATABASE_URL=postgres://vogonweb:vogonweb@localhost:5432/vogonweb
before_script:
  - psql -c "create role vogonweb with password 'vogonweb'; alter role vogonweb createdb; alter role vogonweb login;" -U postgres
script:
  - python manage.py test
