dist: bionic
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11  
services:
  - redis-server
  - postgresql
addons:
    postgresql: '11'
env:
  global:
    - DJANGO_SETTINGS_MODULE=vogon.settings
    - REDIS_URL=redis://
    - CELERY_TASK_SERIALIZER=json
    - DATABASE_URL=postgres://vogonweb:vogonweb@localhost:5432/vogonweb
before_script:
  - psql -c "create role vogonweb with password 'vogonweb'; alter role vogonweb createdb; alter role vogonweb login;" -U postgres
script:
  - python manage.py test
