language: python
python:
  - "2.7"
services:
  - redis-server
  - postgresql
env:
  global:
    - DJANGO_SETTINGS_MODULE=vogon.settings
    - REDIS_URL=redis://
    - CELERY_TASK_SERIALIZER=json
    - DATABASE_URL=postgres://vogonweb:vogonweb@localhost:5432/vogonweb
before_script:
  - psql -c 'create role vogonweb with password vogonweb; create database vogonweb with owner vogonweb; alter role vogonweb creatdb;' -U postgres
script:
  - python manage.py test
