# Generated by Django 2.2 on 2020-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_citespheretoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citespheretoken',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='citespheretoken',
            name='refresh_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
