# Generated by Django 2.2 on 2020-10-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resettoken'),
        ('accounts', '0002_citespheretoken'),
    ]

    operations = [
    ]
