# Generated by Django 2.2 on 2021-07-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20201002_1825'),
        ('accounts', '0003_auto_20201002_2148'),
    ]

    operations = [
    ]
