# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_concept_merged_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='concept_state',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Rejected', b'Rejected'), (b'Approved', b'Approved'), (b'Resolved', b'Resolved'), (b'Merged', b'Merged')], default=b'Pending', max_length=10),
        ),
    ]
