# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_auto_20170329_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Resolved', 'Resolved'), ('Merged', 'Merged')], default='Pending', max_length=10),
        ),
    ]
