# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:57


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0028_auto_20170331_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateappellation',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_appellations', to='annotations.DocumentPosition'),
        ),
    ]
