# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0029_dateappellation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateappellation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_appellations', to='annotations.TextCollection'),
        ),
        migrations.AddField(
            model_name='dateappellation',
            name='stringRep',
            field=models.TextField(blank=True, null=True),
        ),
    ]
