# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:21


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0030_auto_20170331_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='VogonUserDefaultProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_project', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_default_for', to='annotations.TextCollection')),
            ],
        ),
        migrations.AlterField(
            model_name='relationtemplatepart',
            name='object_node_type',
            field=models.CharField(blank=True, choices=[(b'TP', b'Open concept'), (b'CO', b'Specific concept'), (b'DT', b'Date appellation'), (b'RE', b'Relation')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='relationtemplatepart',
            name='source_node_type',
            field=models.CharField(blank=True, choices=[(b'TP', b'Open concept'), (b'CO', b'Specific concept'), (b'DT', b'Date appellation'), (b'RE', b'Relation')], max_length=2, null=True),
        ),
    ]
