# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0031_auto_20170405_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 23, 17, 52, 46, 32329, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationtemplate',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
