# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-27 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    dependencies = [
        ('annotations', '0032_auto_20170523_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_row', models.IntegerField(blank=True, default=0, null=True)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('failed', models.BooleanField(default=False)),
            ],
        ),
    ]
