# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0032_auto_20170523_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtemplate',
            name='use_in_mass_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
