# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-13 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0033_importtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtasks',
            name='current_row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importtasks',
            name='total_rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
