# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0034_csvdownloadlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdownloadlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
