# Generated by Django 2.2 on 2019-08-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0034_auto_20190625_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtemplate',
            name='use_in_mass_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
