# Generated by Django 2.2 on 2019-09-27 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_relationtemplate_use_in_mass_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcollection',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='contributes_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
