# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_csvdownloadlist_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdownloadlist',
            name='path',
        ),
        migrations.AddField(
            model_name='csvdownloadlist',
            name='file_field',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
