# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_auto_20181113_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtasks',
            name='current_row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importtasks',
            name='total_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
