# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0036_auto_20190419_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdownloadlist',
            name='file_field',
            field=models.FileField(null=True, upload_to=b'csv_export/'),
        ),
    ]
