# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-13 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0036_auto_20181113_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importtasks',
            old_name='current_row',
            new_name='c_row',
        ),
    ]
