# Generated by Django 2.2 on 2020-02-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0036_auto_20190927_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationset',
            name='pending',
        ),
    ]
