# Generated by Django 2.2 on 2020-08-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0037_remove_relationset_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vogonuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
