# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-20 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0037_auto_20181113_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtasks',
            name='task_id',
        ),
    ]
