# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-01 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'annotations', '0038_auto_20190501_1657'), (b'annotations', '0039_auto_20190501_1733'), (b'annotations', '0040_auto_20190501_1828')]

    dependencies = [
        ('annotations', '0037_auto_20190422_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdownloadlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 16, 57, 21, 948445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csvdownloadlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 17, 33, 41, 799335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csvdownloadlist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
