# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-21 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0038_remove_importtasks_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importtasks',
            old_name='c_row',
            new_name='current_row',
        ),
    ]
