# Generated by Django 2.2 on 2022-02-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0039_textcollection_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtemplate',
            name='default_mappings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationtemplate',
            name='static_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
