# Generated by Django 2.2 on 2021-08-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0039_textcollection_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellation',
            name='dateStringRep',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appellation',
            name='type',
            field=models.CharField(blank=True, choices=[('concept', 'concept'), ('date', 'date')], default='concept', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='interpretation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concepts.Concept'),
        ),
    ]
