# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0039_auto_20181121_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtasks',
            name='file_name',
            field=models.CharField(max_length=1000),
        ),
    ]
