# Generated by Django 2.2 on 2023-05-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0039_textcollection_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellation',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dateappellation',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
