# Generated by Django 2.2.16 on 2023-09-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0040_auto_20230502_2315'),
        ('annotations', '0040_vogonuser_is_token_reset_required'),
        ('annotations', '0040_csvdownloadlist'),
    ]

    operations = [
    ]
