# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-21 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0040_auto_20181121_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtasks',
            name='current_row',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
