# Generated by Django 2.2.16 on 2023-09-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0041_merge_20230921_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateappellation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='type',
        ),
    ]
