# Generated by Django 2.2 on 2022-02-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0041_vogonuser_is_reset_password_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vogonuser',
            name='is_password_reset_required',
        ),
    ]
