# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0041_auto_20181121_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtasks',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
