# Generated by Django 2.2.16 on 2023-10-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0042_auto_20230921_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='file_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
