# Generated by Django 2.2.16 on 2024-01-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0043_text_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateField(blank=True, help_text='The\n                               publication or creation date of the original\n                               document.', null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(help_text='The\n                             original title of the document.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='textcollection',
            name='quadriga_id',
            field=models.CharField(blank=True, help_text='Use this field to\n                                   specify the ID of an existing project in\n                                   Quadriga with which this project should be\n                                   associated.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vogonuser',
            name='conceptpower_uri',
            field=models.URLField(blank=True, help_text='Advanced: if you\n                                       have an entry for yourself in the\n                                       Conceptpower authority service, please\n                                       enter it here.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vogonuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Un-set\n                                    this field to deactivate a user. This is\n                                    extremely preferable to deletion.'),
        ),
    ]
