# Generated by Django 2.2.16 on 2024-01-31 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0045_auto_20240130_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='annotations.Text'),
        ),
    ]
